# docker-compose.yml
version: "3.8"

services:
  laravel-docker:
    container_name: contento-docker
    build: .
    ports:
      - "9000:80"
      - "4443:443"
      - "5173:5173"
    depends_on:
      - mysql_db
    volumes:
      - db_data:/var/www/html # Map the volume to the Laravel application directory

  mysql_db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: zxc321...
      MYSQL_DATABASE: contento
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db

volumes:
  db_data:
