services:
  laravel-docker:
    container_name: contento-docker
    build: .
    # volumes:
    #   - ./contento.web:/var/www/html
    ports:
      - 9000:80
      - 4443:443
      - 5173:5173

  mysql_db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: zxc321...
      MYSQL_DATABASE: contento
    ports:
      - 13306:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  db_data:
