services:
  laravel-docker:
    container_name: contento-docker
    build: .
    ports:
      - "9000:80"
      - "4443:443"
      - "5173:5173"
    depends_on:
      - mysql_db
    volumes:
      # - laravel_data:/var/www/html # Bind mount for Laravel application directory
      - ./:/var/www/html
      - laravel_data:/var/www/html/contento.web/storage # Keep storage persistent
      - laravel_cache:/var/www/html/contento.web/bootstrap/cache # Ensure cache directory has correct permissions
    labels:
      - docker-volume-backup.stop-during-backup=true
  mysql_db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: zxc321...
      MYSQL_DATABASE: contento
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Volume for MySQL data
    labels:
      - docker-volume-backup.stop-during-backup=true
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db
    volumes:
      - phpmyadmin_data:/var/www/html/phpmyadmin # Volume for phpMyAdmin data (if needed)
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_RETENTION_DAYS: 7
      BACKUP_CRON_EXPRESSION: "0 2 * * *"
      WEBDAV_URL: https://webdav.pcloud.com/
      WEBDAV_PATH: /backup_contento/
      WEBDAV_USERNAME: pavegvar@gmail.com
      WEBDAV_PASSWORD: Domi1329@
    volumes:
      - laravel_data:/backup/laravel_data:ro
      - mysql_data:/backup/mysql_data:ro
      - //c/backups:/backup/backups
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  laravel_data: # Volume for Laravel application data
  laravel_cache: # Volume for Laravel application data
  mysql_data: # Volume for MySQL data
  phpmyadmin_data: # Volume for phpMyAdmin data (if needed)
