version: "3.8"

services:
  laravel-docker:
    container_name: contento-docker
    build: .
    ports:
      - "9000:80"
      - "4443:443"
      - "5173:5173"
    depends_on:
      - mysql_db
    volumes:
      - laravel_data:/var/www/html # Bind mount for Laravel application directory

  mysql_db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: zxc321...
      MYSQL_DATABASE: contento
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Volume for MySQL data

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db
    volumes:
      - phpmyadmin_data:/var/www/html # Volume for phpMyAdmin data (if needed)

volumes:
  laravel_data: # Volume for Laravel application data
  mysql_data: # Volume for MySQL data
  phpmyadmin_data: # Volume for phpMyAdmin data (if needed)
